<div class="card topnav-right">
    <div class="card-body card-content-right">
        <ul class="list-inline m-0 p-0 d-flex align-items-center justify-content-around">
            <li class="nav-item nav-icon dropdown">
                <a href="/?section=login" class="search-toggle dropdown-toggle nav-icon-1">
                <i class="">
                    <svg class="svg-icon" id="iq-auth-1-1" width="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                    </svg>
                </i>
                </a>
            </li>
            <li class="nav-item nav-icon dropdown pl-3"> 
                <a href="/?section=reg" class="search-toggle dropdown-toggle nav-icon-1">
                <i class="">
                    <svg  class="svg-icon" id="iq-auth-1-2" width="20"  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
                    </svg>
                </i>
                </a>
            </li>  
        </ul>
    </div>           
 </div>