<?php require_once("top.phtml"); ?>
    <?php require_once("sidebar_right.phtml"); ?>
    
    <!-- Wrapper Start -->
  	<?php require_once("wrapper.phtml"); ?>
  	<?php require_once("sidebar_left.phtml"); ?>

       <div class="content-page">
        <div class="container-fluid">
          <div class="desktop-header">
              <div class="card card-block topnav-left">
                  <div class="card-body d-flex align-items-center">
                      <div class="d-flex justify-content-between">
                          <h4 class="text-capitalize">Добро Пожаловать в Ту_Душку!</h4>
                      </div>
                  </div>
              </div>
             
              	<?php require_once ("card_topnav_right.phtml"); ?>
                   </div>
      <div class="container-fluid">
         <div class="row">
            <div class="col-lg-12">
               <form action="" method="POST">
                <input type="submit" name="submit" value="Добавить в БД">
                </form>
            </div>
         </div>
      </div>
      </div>
    </div>
    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    <?php require_once("footer.phtml"); ?>
   	<?php require_once("bottom.phtml"); ?>
  </body>
</html>