<?php require_once("top.phtml"); ?>
    <!-- Wrapper Start -->

  	<?php require_once("sidebar_left.phtml"); ?>

       <div class="content-page">
        <div class="container-fluid">
          <div class="desktop-header">
              <div class="card card-block topnav-left">
                  <div class="card-body d-flex align-items-center">
                      <div class="d-flex justify-content-between">
                          <h4 class="text-capitalize">Добро Пожаловать в Ту_Душку!</h4>
                      </div>
                  </div>
              </div>
          </div>
      <div class="container-fluid">
         <div class="row">
            <div class="col-lg-12">
               <form action="" method="GET">
               		<a href="/?section=project_store" class="btn btn-outline-primary svg-icon">
                    <span>Создать Новый Проект</span>
                  </a>
                  <div class="my-error" style="padding-top: 5%">
                    <?php if ($flash->hasError('tag_notask_delete')): ?>
                      <div><?php echo $flash->getError('tag_notask_delete'); ?></div>
                    <?php endif; ?>
                  </div>
                </form>
            </div>
         </div>
      </div>
      </div>
    </div>
    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    <?php require_once("footer.phtml"); ?>
   	<?php require_once("bottom.phtml"); ?>
    <?php if ($flash->hasSuccess('tag_notask_delete')): ?>
      <script>
        toastr.success('Теги без задач успешно удалены!');
      </script>
    <?php endif; ?>
  </body>
</html>