<?php require_once("top.phtml"); ?>
    <?php require_once("sidebar_right.phtml"); ?>
    
    <!-- Wrapper Start -->
    <?php require_once("wrapper.phtml"); ?>
    <?php require_once("sidebar_left.phtml"); ?>

       <div class="content-page">
        <div class="container-fluid">
          <div class="desktop-header">
              <div class="card card-block topnav-left">
                  <div class="card-body write-card">
                    <div class="d-flex align-items-center justify-content-between">
                          <h4 class="text-capitalize">Список моих проектов</h4>
                          <a href="/?section=project_store" class="btn btn-outline-primary svg-icon">
                            <svg  width="20" class="svg-icon" id="new-note-back" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
                            </svg>
                            <span>Новый проект</span>
                        </a>
                      </div>
                  </div>
              </div>
            <?php require_once ("card_topnav_right.phtml"); ?>
         </div>
      <div class="my-error">
        <?php foreach ($errors as $error): ?>
          <?php echo $error."<br>"; ?>
        <?php endforeach; ?>
      </div><br>
      <div class="container-fluid">
         <div class="row">
            <div class="col-lg-12">
               <div class="card card-block card-stretch card-height note-table">
                  <div class="card-body custom-notes-space">
                     <div class="table-responsive">
                        <table id="tree-table-9" class="table tree mb-0 tbl-server-info">
                           <thead class="bg-white text-uppercase">
                              <tr class="ligth">
                                 <th>Название проекта</th>
                                 <th>Кем Создан</th>
                                 <th>Обновлен</th>
                                 <th>Доступ</th>
                                 <th>Редактировать/Удалить</th>
                              </tr>
                           </thead>
                           <tbody>
                            <?php foreach($items as $item):?>
                             <tr data-id="<?php echo ($item['data-level'] == 1 ? 'p' : 't').$item['data-id'];?>" data-parent="<?php echo  ($item['data-level'] == 2 ? 'p' : '').$item['data-parent'];?>" data-level="<?php echo $item['data-level'];?>">
                                 <td data-column="name"><?php echo $item['name'];?></td>
                                 <td>Bud Wiser</td>
                                 <td>Dec 4</td>
                                 <td><i class="las la-lock mr-3 font-size-20"></i>Only You</td>
                                 <td>
                                    <div>
                                        <a href="/?section=project_store&id=<?php echo ($item['data-level'] == 1 ? 'p' : 't').$item['data-id'];?>" class="badge badge-success mr-3 edit-note"><i class="las la-pen mr-0"></i></a>
                                        <a href="/?section=project&operation=delete&id=<?php echo ($item['data-level'] == 1 ? 'p' : 't').$item['data-id'];?>" class="badge badge-danger"><i class="las la-trash-alt mr-0"></i></a>
                                    </div>
                                 </td>
                              </tr>
                            <?php endforeach; ?>
                           </tbody>
                        </table>
                     </div>
                  </div>
               </div>
            </div>
        </div>
      </div>
      </div>
    </div>
    
    <!-- Page end  -->
</div>
   <!-- Modal -->
   
      </div>
    </div>
    <!-- Wrapper End-->
    <?php require_once("footer.phtml"); ?>
    <?php require_once("bottom.phtml"); ?>
  </body>
</html>