<?php require_once("top.phtml"); ?>
    <?php require_once("sidebar_right.phtml"); ?>
    
    <!-- Wrapper Start -->
    <?php require_once("wrapper.phtml"); ?>
    <?php require_once("sidebar_left.phtml"); ?>

       <div class="content-page">
        <div class="container-fluid">
          <div class="desktop-header">
              <div class="card card-block topnav-left">
                  <div class="card-body d-flex align-items-center">
                      <div class="d-flex justify-content-between">
                          <h4 class="text-capitalize">Список моих проектов</h4>
                      </div>
                  </div>
              </div>
             
                <?php require_once ("card_topnav_right.phtml"); ?>
                   </div>
      <div class="container-fluid">
         <div class="row">
            <div class="col-lg-12">
               <div class="card card-block card-stretch card-height note-table">
                  <div class="card-body custom-notes-space">
                     <div class="table-responsive">
                        <table id="tree-table-9" class="table tree mb-0 tbl-server-info">
                           <thead class="bg-white text-uppercase">
                              <tr class="ligth">
                                 <th>Название проекта</th>
                                 <th>Кем Создан</th>
                                 <th>Обновлен</th>
                                 <th>Доступ</th>
                                 <th>Редактировать/Удалить</th>
                              </tr>
                           </thead>
                           <tbody>
                            <?php foreach($tasks_and_projects as $task_and_project):?>
                             <tr data-id="<?php echo $task_and_project['project_id'];?>" data-parent="0" data-level="1">
                                 <td data-column="name"><?php echo $task_and_project['project_name'];?></td>
                                 <td>Bud Wiser</td>
                                 <td>Dec 4</td>
                                 <td><i class="las la-lock mr-3 font-size-20"></i>Only You</td>
                                 <td>
                                    <div>
                                        <a href="#" class="badge badge-success mr-3 edit-note" data-toggle="modal" data-target="#edit-note"><i class="las la-pen mr-0"></i></a>
                                        <a href="#" class="badge badge-danger" data-extra-toggle="delete" data-closest-elem="tr"data-extra-toggle="delete" data-closest-elem="tr"><i class="las la-trash-alt mr-0"></i></a>
                                    </div>
                                 </td>
                              </tr>
                              <tr data-id="<?php echo $task_and_project['id'];?>" data-parent="<?php echo $task_and_project['project_id'];?>" data-level="2">
                                 <td data-column="name"><?php echo $task_and_project['name']; ?></td>
                                 <td>Bud Wiser</td>
                                 <td>Dec 4</td>
                                 <td><i class="las la-lock mr-3 font-size-20"></i>Only You</td>
                                 <td>
                                    <div>
                                        <a href="#" class="badge badge-success mr-3 edit-note" data-toggle="modal" data-target="#edit-note"><i class="las la-pen mr-0"></i></a>
                                        <a href="#" class="badge badge-danger" data-extra-toggle="delete" data-closest-elem="tr"data-extra-toggle="delete" data-closest-elem="tr"><i class="las la-trash-alt mr-0"></i></a>
                                    </div>
                                 </td>
                              </tr>
                            <?php endforeach; ?>
                           </tbody>
                        </table>
                     </div>
                  </div>
               </div>
            </div>
        </div>
      </div>
      </div>
    </div>
    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    <?php require_once("footer.phtml"); ?>
    <?php require_once("bottom.phtml"); ?>
  </body>
</html>