<?php require_once("top.phtml"); ?>
    
    <!-- Wrapper Start -->
  	<?php require_once("sidebar_left.phtml"); ?>

       <div class="content-page">
     <div class="container-fluid">        
        <div class="desktop-header">
            <div class="card card-block topnav-left">
                <div class="card-body write-card">
                    <div class="d-flex align-items-center justify-content-between">
                        <h4><?php echo @$_GET['id'] ? 'Редактировать':'Новый';?> Проект</h4>
                    </div>
                </div>
            </div>
        </div>
        <?php if (isset($errors['project_not_found'])): ?>
            <div class="my-error"><?php echo $errors['project_not_found'];?></div>
            <?php else: ?>
            <div class="row">
            <div class="col-lg-12">                
                <div class="card card-block card-stretch pb-2">
                    <div class="card-body write-card pb-4">
                        <div class="row">
                            <div class="col-md-8">
                                <form action="" method="POST">
                                    <div class="form-group">
                                        <label class="label-control">Название Проекта</label>
                                        <input type="text" class="form-control" name="title" placeholder="Введите название" value="<?php echo @$fields['title'];?>" data-change="input" data-custom-target="#note-title">
                                    </div>
                                    <?php if (isset($errors['title'])) : ?>
                                        <label class="my-error" for="title"><?php echo $errors['title']."<br>"; ?></label>
                                     <?php endif; ?>
                                    <span>
                                        <button name ="submit" class="btn btn-primary ml-1">
                                            <svg width="20" class="svg-icon" id="new-note-save" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                                            </svg>
                                            Сохранить
                                        </button>
                                    </span>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="default-note d-none">
            <div class="card card-block card-stretch card-height card-bottom-border-info note-detail" id="update-note">
                <div class="card-header d-flex justify-content-between pb-1">
                    <div class="icon iq-icon-box-2 icon-border-info rounded" id="note-icon">
                        <svg width="23" class="svg-icon" id="iq-main-01" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                    </div>
                    <div class="card-header-toolbar d-flex align-items-center">
                        <div class="dropdown">
                            <span class="dropdown-toggle dropdown-bg" id="dropdownMenuButton4"
                                data-toggle="dropdown" aria-expanded="false" role="button">
                                <i class="ri-more-fill"></i>
                            </span>
                            <div class="dropdown-menu dropdown-menu-right"
                                aria-labelledby="dropdownMenuButton4" style="">
                                <a href="#" class="dropdown-item new-note1" data-toggle="modal" data-custom-target="#new-note1"><i class="ri-eye-line mr-3"></i>Предпросмотр</a>
                                <a class="dropdown-item" href="#"><i class="las la-trash-alt mr-3"></i>Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body rounded">
                    <h4 class="card-title text-ellipsis short-1" id="note-title">Пример Заголовка</h4>
                    <p class="mb-3 text-ellipsis short-6" id="note-description">Пример Отображения Текста</p>
                </div>
                <div class="card-footer">
                    <div class="d-flex align-items-center justify-content-between note-text note-text-info"> 
                        <a href="#" class=""><i class="las la-user-friends mr-2 font-size-20"></i>Только Для Меня</a>
                        <a href="#" class=""><i class="las la-calendar mr-2 font-size-20"></i><span id="note-reminder-date">01 Jan 2021</span></a>
                    </div>
                </div>
            </div>
        </div>
        <?php endif; ?>
        
    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    <?php require_once("footer.phtml"); ?>
   	<?php require_once("bottom.phtml"); ?>
  </body>
</html>