<?php require_once("top.phtml"); ?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <!-- Wrapper Start -->
    <div id="loading">
          <div id="loading-center">
          </div>
    </div>
    <!-- loader END -->
    
      <div class="wrapper">
        <section class="login-content">
           <div class="container h-100">
              <div class="row justify-content-center align-items-center height-self-center">
                 <div class="col-md-5 col-sm-12 col-12 align-self-center">
                    <div class="sign-user_card">
                       <div class="logo-detail">            
                             <div class="d-flex align-items-center"><img src="images/logo.png" class="img-fluid rounded-normal light-logo logo" alt="logo"> <h4 class="logo-title ml-3">Ту_Душка</h4></div>
                       </div> 
                       <div id="s1">
                       <h3 class="mb-2">Зарегистрироваться</h3>
                       <p>Создай свой аккаунт</p>
                       <form action="#">
                          <div class="row"> 
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input id="firstname" class="floating-input form-control" type="text" placeholder="Имя">
                                   <div class="my-error" id="error-firstname"></div>
                                </div>
                             </div>
                             
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input id="lastname" class="floating-input form-control" type="text" placeholder="Фамилия">
                                </div>
                             </div>
                            
                             <div class="col-lg-12">
                                <div class="floating-label form-group">
                                   <input id="phone" class="floating-input form-control" type="text" placeholder="Телефон в формате +78001001010">
                                   <div class="my-error" id="error-phone"></div>
                                   <div class="my-warning" id="warning-phone"></div>
                                </div>
                             </div>
                             
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input id="password" class="floating-input form-control" type="password" placeholder="Пароль">
                                  <div class="my-error" id="error-password"></div>
                                </div>
                             </div>
                             
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input id="re_password" class="floating-input form-control" type="password" placeholder="Повтори пароль">
                                   <div class="my-error" id="error-re_password"></div>
                                </div>
                             </div>
                             
                             <div class="col-lg-12">
                                <div class="custom-control custom-checkbox mb-3 text-left">
                                   <input id="customCheck1" type="checkbox" name="agree" class="custom-control-input" value="">
                                   <label class="custom-control-label" for="customCheck1">Я согласен с пользовательским соглашением</label>
                                   <div class="my-error" id="error-agree"></div>
                                </div>
                             </div>
                              <div class="col-lg-12">
                               <div class="g-recaptcha" data-sitekey="6LfDzX0aAAAAAEHlspKjdFAwe2oT_DiEz7FLfSIv"></div>
                               <div class="my-error" id="error-g-recaptcha-response"></div>
                             </div>
                          <div class="col-lg-12">
                          <button name="reg-submit" class="btn btn-primary">Зарегистрироваться</button>
                          </div>
                        </div>
                        </div>
                        <div id="s2" style="display: none;">
                          <div class="col-lg-12">
                            <div class="floating-label form-group">
                               <input id="code" class="floating-input form-control" type="text" placeholder="Введите последние 6-ть цифр номера со входящего звонка">
                            </div>
                            <div class="my-error"></div>
                          </div>
                           <div class="col-lg-12">
                          <button name="reg-finish" class="btn btn-primary">Завершить регистрацию</button>
                          </div>
                        </div>
                      </form>
                      <div id="s3" style="display: none;">
                            <div class="col-lg-12">
                              <div class="floating-label  form-group">
                                <span>Регистрация прошла успешно!</span>
                              </div>
                            </div>
                          </div>
                    </div>
                 </div>
              </div>
           </div>
        </section>
      </div>

    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    
   	<?php require_once("bottom.phtml"); ?>
    <?php if ($flash->hasSuccess('tag_notask_delete')): ?>
      <script type="text/javascript">
        toastr.success('Теги без задач успешно удалены!');
      </script>
    <?php endif; ?>
    <script type="text/javascript">
      $("[name=reg-submit]").click(function (e) {
        e.preventDefault();
        
        $.ajax({
          url: "/?section=reg_ajax",
          method: "POST",
          data: {
            "firstname": $("#firstname").val(),
            "lastname": $("#lastname").val(),
            "phone": $("#phone").val(),
            "password": $("#password").val(),
            "re_password": $("#re_password").val(),
            "agree": $('#customCheck1').is(':checked'),
            "g-recaptcha-response": grecaptcha.getResponse()
          }
        }).done(function (r) {
          console.log(r);
          if (r.data !== undefined) {
            $("#s1").hide(200);
            $("#s2").show(200);
          } else if (r.errors !== undefined) {
            $(".my-error").html("");
            for(key in r.errors) {
              $("#error-"+key).html(r.errors[key]);
            }
          }
        });
      });

      $("[name=reg-finish]").click(function (e){
        e.preventDefault();

        $.ajax({
          url: "/?section=reg_confirm_ajax",
          method: "POST",
          data: {
            "code": $("#code").val()
          }
        }).done(function (r) {
         // $("[name=success],[name=errors]").html("");

          if (r.data !== undefined) {
            $("#s2").hide(200);
            $("#s3").show(200);
            location.href = "http://todo.local/";
          } else if (r.errors !== undefined) {
            $(".my-error").html("");
            for(key in r.errors) {
              $(".my-error").html(r.errors[key]);
            }
          }
        });
      });
    </script>
  </body>
</html>