<?php require_once("top.phtml"); ?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <!-- Wrapper Start -->
    <div id="loading">
          <div id="loading-center">
          </div>
    </div>
    <!-- loader END -->
    
      <div class="wrapper">
      <form method="POST">
        <section class="login-content">
           <div class="container h-100">
              <div class="row justify-content-center align-items-center height-self-center">
                 <div class="col-md-5 col-sm-12 col-12 align-self-center">
                    <div class="sign-user_card">
                       <div class="logo-detail">            
                             <div class="d-flex align-items-center"><img src="images/logo.png" class="img-fluid rounded-normal light-logo logo" alt="logo"> <h4 class="logo-title ml-3">Ту_Душка</h4></div>
                       </div>  
                       <h3 class="mb-2">Зарегистрироваться</h3>
                       <p>Создай свой аккаунт</p>
                       <form>
                          <div class="row">
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input name="firstname" class="floating-input form-control" type="text" placeholder="Имя" value="<?php echo @$_POST['firstname']; ?>">
                                   <?php if (isset($errors['firstname'])) : ?>
                                     <div class="my-error"><?php echo $errors['firstname']; ?></div>
                                   <?php endif; ?>
                                </div>
                             </div>
                             
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input name="lastname" class="floating-input form-control" type="text" placeholder="Фамилия" value="<?php echo @$_POST['lastname']; ?>">
                                </div>
                             </div>
                            
                             <div class="col-lg-12">
                                <div class="floating-label form-group">
                                   <input name="phone" class="floating-input form-control" type="text" placeholder="Телефон в формате +78001001010" value="<?php echo @$_POST['phone']; ?>">
                                   <?php if (isset($errors['phone'])):?>
                                    <div class="my-error"><?php echo $errors['phone']; ?></div>
                                   <?php endif; ?>
                                </div>
                             </div>
                             
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input name="password" class="floating-input form-control" type="password" placeholder="Пароль" value="<?php echo @$_POST['password']; ?>">
                                   <?php if (isset($errors['password'])): ?>
                                    <div class="my-error"><?php echo $errors['password']; ?></div>
                                  <?php endif; ?>
                                </div>
                             </div>
                             
                             <div class="col-lg-6">
                                <div class="floating-label form-group">
                                   <input name="re-password" class="floating-input form-control" type="password" placeholder="Повтори пароль" value="<?php echo @$_POST['re-password']; ?>">
                                   <?php if (isset($errors['re-password'])): ?>
                                    <div class="my-error"><?php echo $errors['re-password']; ?></div>
                                   <?php endif; ?>
                                </div>
                             </div>
                             
                             <div class="col-lg-12">
                                <div class="custom-control custom-checkbox mb-3 text-left">
                                   <input name="checkbox" type="checkbox" class="custom-control-input" id="customCheck1">
                                   <label class="custom-control-label" for="customCheck1">Я согласен с пользовательским соглашением</label>
                                   <?php if (isset($errors['checkbox'])): ?>
                                    <div class="my-error"><?php echo $errors['checkbox']; ?></div>
                                   <?php endif; ?>
                                </div>
                             </div>
                          </div>
                          <div class="g-recaptcha" data-sitekey="6LfDzX0aAAAAAEHlspKjdFAwe2oT_DiEz7FLfSIv"></div>
                          <?php if (isset($errors['g-recaptcha-response'])): ?>
                            <div class="my-error"><?php echo $errors['g-recaptcha-response']; ?></div>
                          <?php endif; ?>
                          <br/>
                          <button name="reg-submit" type="submit" class="btn btn-primary">Зарегистрироваться</button>
                          <p class="mt-3 mb-0">
                             У меня уже есть аккаунт <a href="/?section=login" class="text-primary"><b>Войти</b></a>
                          </p>
                       </form>
                    </div>
                 </div>
              </div>
           </div>
        </section>
      </form>
      </div>

    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    
   	<?php require_once("bottom.phtml"); ?>
    <?php if ($flash->hasSuccess('tag_notask_delete')): ?>
      <script>
        toastr.success('Теги без задач успешно удалены!');
      </script>
    <?php endif; ?>
  </body>
</html>