<div class="iq-sidebar  sidebar-default ">
    <div class="iq-sidebar-logo d-flex align-items-center justify-content-between">
        <a href="/?section=index" class="header-logo">
            <img src="images/logo.png" class="img-fluid rounded-normal light-logo" alt="logo"> <h4 class="logo-title ml-3">Проекты</h4>
        </a>
        <div class="iq-menu-bt-sidebar">
            <i class="las la-times wrapper-menu"></i>
        </div>
    </div>    
    <div class="data-scrollbar" data-scroll="1">
        <div class="sidebar-caption dropdown">
              <a href="#" class="iq-user-toggle d-flex align-items-center justify-content-between" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="caption">
                    <div class="row">
                        <div class="col-1">
                            <svg width="20" class="svg-icon" id="iq-main-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                               <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                            </svg> 
                        </div> 
                        <div class="col-3">                                                   
                            <h5 class="mb-0 line-height" style="text-align: left;">Теги</h5>
                        </div>
                    </div> 
                  </div>
                  <i class="las la-angle-down"></i>
              </a>
              <div class="dropdown-menu w-100 border-0 my-2" aria-labelledby="dropdownMenuButton">
                <?php foreach ($tags as $tag) : ?>
                    <?php if ($tag['count'] > 0): ?>
                        <a class="dropdown-item mb-2" href="#<?php echo $tag['id']; ?>">
                            <!--<?php foreach ($first_letters as $value) : ?>
                                <?php if ($tag['first_letter'] == $value): ?>
                                    <span class="mt-2"><?php echo $value; ?></span>
                                <?php endif ?>
                            <?php endforeach; ?>-->
                            <span class="mt-2"><?php echo $tag['name']; ?></span>
                            <span class="mt-2 col-2" style="color: rgba(0,0,0,0.5);">(<?php echo $tag['count']; ?>)</span>
                        </a>
                    <?php else: ?>
                        <a class="dropdown-item mb-2" href="#">
                            <span class="mt-2"><?php echo $tag['name']; ?></span>
                        </a>
                    <?php endif ?>
                <?php endforeach; ?>
              </div>
          </div>
        <div class="sidebar-btn dropdown mb-3">
            <a href="/?section=project_store" class="btn btn-primary pr-5 position-relative iq-user-toggle d-flex align-items-center justify-content-between" style="height: 40px;"><span class="btn-title"><i class="ri-add-line mr-3"></i>Создать Проект</span></a>
        </div>
        <nav class="iq-sidebar-menu">
            <div id="iq-sidebar-toggle" class="iq-menu">
                <?php foreach ($projects as $p): ?>
                    <div class="active">
                        <a href="/?section=project&id=<?php echo $p['id']; ?>" class="svg-icon">
                            <i>
                                <svg class="svg-icon" id="iq-main-1" width="20" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
                                </svg>
                            </i>
                            <span><?php echo $p['name']; ?></span>
                        </a>
                        <a href="/?section=project_deleted&id=<?php echo $p['id']; ?>" class="svg-icon" style="float: right;">
                            <svg width="20" class="svg-icon" id="iq-main-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </a>
                        <a href="/?section=project_store&id=<?php echo $p['id']; ?>" class="svg-icon" style="float: right;">
                            <svg width="23" height="23" class="svg-icon" id="iq-main-04" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                            </svg>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </nav>
    </div>
</div> 