<?php require_once("top.phtml"); ?>
    
    <!-- Wrapper Start -->
  	<?php require_once("sidebar_left.phtml"); ?>

       <div class="content-page">
     <div class="container-fluid">        
       
        <?php if (isset($errors)): ?>
          <?php foreach ($errors as $error): ?>
              <div class="my-error"><?php echo $error;?></div>
          <?php endforeach; ?>
        <?php endif; ?>
       <div class="desktop-header">
          <div class="card card-block topnav-left">
              <div class="card-body write-card">
                  <div class="d-flex align-items-center justify-content-between">
                      <h4>Удаление прошло успешно!</h4>
                  </div>
              </div>
          </div>
      </div>
        
        
    
    <!-- Page end  -->
</div>
  </div>
</div>
    <!-- Wrapper End-->
    <?php require_once("footer.phtml"); ?>
   	<?php require_once("bottom.phtml"); ?>
  </body>
</html>