<?php require_once("top.phtml"); ?>
    <!-- Wrapper Start -->

  	<?php require_once("sidebar_left.phtml"); ?>

      <div class="content-page">
        <div class="container-fluid">
          <?php if (isset($errors['task_not_found'])): ?>
            <div class="my-error"><?php echo $errors['task_not_found']; ?></div>
            <?php else: ?>
              <div class="desktop-header">
                  <div class="card card-block topnav-left">
                      <div class="card-body d-flex align-items-center">
                          <div class="d-flex justify-content-between">
                              <h2 class="text-capitalize">Задача: <?php echo $task['name']; ?></h2>
                          </div>
                      </div>
                  </div>
              </div>
                <div class="row">
                <div class="col-lg-12">
                   <form action="" method="GET">
                   	<h3 class="text-capitalize">Список Подзадач</h3>
                    <div class="card-body d-flex align-items-center">
                    <a href="/?section=subtask_store&task_id=<?php echo $task['id']; ?>" class="btn btn-outline-primary svg-icon">
                        <span>Добавить подзадачу</span>
                    </a>
                    </div>
                    <?php foreach ($subtasks as $subtask): ?>
                      <div class="form-check col-4">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" <?php echo $subtask['status_completed'] == 1 ? 'checked' : ''; ?>>
                        <label class="form-check-label" for="flexCheckDefault">
                          <?php echo $subtask['name']; ?>
                        </label>
                        <a href="/?section=subtask&operation=delete&subtask_id=<?php echo $subtask['id']; ?>" class="svg-icon" style="float: right;">
                            <svg width="20" class="svg-icon" id="iq-main-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </a>
                        <a href="/?section=subtask_store&subtask_id=<?php echo $subtask['id']; ?>&task_id=<?php echo $task['id']; ?>" class="svg-icon" style="float: right;">
                            <svg width="23" height="23" class="svg-icon" id="iq-main-04" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                            </svg>
                        </a>
                      </div>
                    <?php endforeach; ?>
                    </form>
                </div>
              </div>
          <?php endif; ?>
    <!-- Page end  -->
        </div>
      </div>
    </div>
    <!-- Wrapper End-->
  <?php require_once("footer.phtml"); ?>
 	<?php require_once("bottom.phtml"); ?>

  </body>
</html>