<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>ToDo | Ту_Душка</title>
      
      <!-- Favicon -->
      <link rel="shortcut icon" href="images/favicon.ico" />
      
      <link rel="stylesheet" href="css/backend.min.css?v=1.0.0">
      <link rel="stylesheet" href="/vendor/@fortawesome/fontawesome-free/css/all.min.css">
      <link rel="stylesheet" href="../vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css">
      <link rel="stylesheet" href="../vendor/remixicon/fonts/remixicon.css">
      <link rel="stylesheet" href="../vendor/@icon/dripicons/dripicons.css">
      
      <link rel='stylesheet' href='../vendor/fullcalendar/core/main.css' />
      <link rel='stylesheet' href='../vendor/fullcalendar/daygrid/main.css' />
      <link rel='stylesheet' href='../vendor/fullcalendar/timegrid/main.css' />
      <link rel='stylesheet' href='../vendor/fullcalendar/list/main.css' />
      <link rel="stylesheet" href="../vendor/mapbox/mapbox-gl.css">

      <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
      <link rel="stylesheet" href="https://code.jquery.com/jquery-3.4.1.min.js">

  </head>
  <body class="noteplus-layout  ">
  